In [ ]:
# KNN algo, Sklearn, Dataset extraction with only python
#The iris dataset has been provided in the drive

!ls

sample_data


In [ ]:
#how to upload file from your computer in google colab
from google.colab import files
uploaded = files.upload()

Saving iris_dataset.txt to iris_dataset.txt


In [ ]:
!ls

'iris (1).txt'	 iris_dataset.txt   iris.txt   sample_data


In [ ]:
#reading the file lines
lines=[]
#change name
with open('iris_dataset.txt') as f:
    lines = f.read().splitlines()
    
print(lines[0:4])

['5.1,3.5,1.4,0.2,Iris-setosa', '4.9,3.0,1.4,0.2,Iris-setosa', '4.7,3.2,1.3,0.2,Iris-setosa', '4.6,3.1,1.5,0.2,Iris-setosa']


In [ ]:
# splitting each sample into attributes
wanted_lines = []
for i in range(0,len(lines)):
  line = lines[i].split(",")
  wanted_lines.append(line)
  
print(wanted_lines[0:4])

[['5.1', '3.5', '1.4', '0.2', 'Iris-setosa'], ['4.9', '3.0', '1.4', '0.2', 'Iris-setosa'], ['4.7', '3.2', '1.3', '0.2', 'Iris-setosa'], ['4.6', '3.1', '1.5', '0.2', 'Iris-setosa']]


In [ ]:
# getting a view at the unique outputs
outputs = []
for i in range(0,len(wanted_lines)):
  outputs.append(wanted_lines[i][-1])
output_set = set(outputs)
print(output_set)

{'Iris-virginica', '', 'Iris-setosa', 'Iris-versicolor'}


In [ ]:
# converting string outputs to values and keeping in dictionary
output_dict={}
i=0
for element in output_set:
  print(element)
  output_dict[element] = i
  i=i+1
print(output_dict)

Iris-virginica

Iris-setosa
Iris-versicolor
{'Iris-virginica': 0, '': 1, 'Iris-setosa': 2, 'Iris-versicolor': 3}


In [ ]:
# replacing string outputs with dictionary ints
for i in range(0,len(wanted_lines)):
  wanted_lines[i][-1] = output_dict[wanted_lines[i][-1]]
print(wanted_lines)

[['5.1', '3.5', '1.4', '0.2', 2], ['4.9', '3.0', '1.4', '0.2', 2], ['4.7', '3.2', '1.3', '0.2', 2], ['4.6', '3.1', '1.5', '0.2', 2], ['5.0', '3.6', '1.4', '0.2', 2], ['5.4', '3.9', '1.7', '0.4', 2], ['4.6', '3.4', '1.4', '0.3', 2], ['5.0', '3.4', '1.5', '0.2', 2], ['4.4', '2.9', '1.4', '0.2', 2], ['4.9', '3.1', '1.5', '0.1', 2], ['5.4', '3.7', '1.5', '0.2', 2], ['4.8', '3.4', '1.6', '0.2', 2], ['4.8', '3.0', '1.4', '0.1', 2], ['4.3', '3.0', '1.1', '0.1', 2], ['5.8', '4.0', '1.2', '0.2', 2], ['5.7', '4.4', '1.5', '0.4', 2], ['5.4', '3.9', '1.3', '0.4', 2], ['5.1', '3.5', '1.4', '0.3', 2], ['5.7', '3.8', '1.7', '0.3', 2], ['5.1', '3.8', '1.5', '0.3', 2], ['5.4', '3.4', '1.7', '0.2', 2], ['5.1', '3.7', '1.5', '0.4', 2], ['4.6', '3.6', '1.0', '0.2', 2], ['5.1', '3.3', '1.7', '0.5', 2], ['4.8', '3.4', '1.9', '0.2', 2], ['5.0', '3.0', '1.6', '0.2', 2], ['5.0', '3.4', '1.6', '0.4', 2], ['5.2', '3.5', '1.5', '0.2', 2], ['5.2', '3.4', '1.4', '0.2', 2], ['4.7', '3.2', '1.6', '0.2', 2], ['4.8', '

In [ ]:
# Converting all string attributes into floats
import numpy as np

for i in range(0,len(wanted_lines)):
  for j in range(0,len(wanted_lines[0])):
    wanted_lines[i][j] = float(wanted_lines[i][j])

IndexError: ignored

In [ ]:
print(np.array(wanted_lines))

[[5.1 3.5 1.4 0.2 1. ]
 [4.9 3.  1.4 0.2 1. ]
 [4.7 3.2 1.3 0.2 1. ]
 [4.6 3.1 1.5 0.2 1. ]
 [5.  3.6 1.4 0.2 1. ]
 [5.4 3.9 1.7 0.4 1. ]
 [4.6 3.4 1.4 0.3 1. ]
 [5.  3.4 1.5 0.2 1. ]
 [4.4 2.9 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.4 3.7 1.5 0.2 1. ]
 [4.8 3.4 1.6 0.2 1. ]
 [4.8 3.  1.4 0.1 1. ]
 [4.3 3.  1.1 0.1 1. ]
 [5.8 4.  1.2 0.2 1. ]
 [5.7 4.4 1.5 0.4 1. ]
 [5.4 3.9 1.3 0.4 1. ]
 [5.1 3.5 1.4 0.3 1. ]
 [5.7 3.8 1.7 0.3 1. ]
 [5.1 3.8 1.5 0.3 1. ]
 [5.4 3.4 1.7 0.2 1. ]
 [5.1 3.7 1.5 0.4 1. ]
 [4.6 3.6 1.  0.2 1. ]
 [5.1 3.3 1.7 0.5 1. ]
 [4.8 3.4 1.9 0.2 1. ]
 [5.  3.  1.6 0.2 1. ]
 [5.  3.4 1.6 0.4 1. ]
 [5.2 3.5 1.5 0.2 1. ]
 [5.2 3.4 1.4 0.2 1. ]
 [4.7 3.2 1.6 0.2 1. ]
 [4.8 3.1 1.6 0.2 1. ]
 [5.4 3.4 1.5 0.4 1. ]
 [5.2 4.1 1.5 0.1 1. ]
 [5.5 4.2 1.4 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [5.  3.2 1.2 0.2 1. ]
 [5.5 3.5 1.3 0.2 1. ]
 [4.9 3.1 1.5 0.1 1. ]
 [4.4 3.  1.3 0.2 1. ]
 [5.1 3.4 1.5 0.2 1. ]
 [5.  3.5 1.3 0.3 1. ]
 [4.5 2.3 1.3 0.3 1. ]
 [4.4 3.2 1.3 0.2 1. ]
 [5.  3.5 1

In [ ]:
#Train, test, validation split with probability

import random

Train = []
Test = []
Validation = []

for i in range(0, len(wanted_lines)):
  num = random.uniform(0, 1)
  if(num>0.7 and num <= 0.85):
    Validation.append(wanted_lines[i])
  elif(num>0.85 and num<=1.0):
    Test.append(wanted_lines[i])
  else:
    Train.append(wanted_lines[i])

print(len(Train))
print(len(Test))
print(len(Validation))

112
23
16


In [ ]:
print(Train)
print(Validation)
print(Test)
#These will be our train, test and validation set

# Run the above cells only once for getting these 3 sets. Then write the KNN algo

[[4.7, 3.2, 1.3, 0.2, 2.0], [4.6, 3.1, 1.5, 0.2, 2.0], [5.0, 3.6, 1.4, 0.2, 2.0], [5.4, 3.9, 1.7, 0.4, 2.0], [4.6, 3.4, 1.4, 0.3, 2.0], [4.9, 3.1, 1.5, 0.1, 2.0], [5.4, 3.7, 1.5, 0.2, 2.0], [4.8, 3.4, 1.6, 0.2, 2.0], [4.8, 3.0, 1.4, 0.1, 2.0], [4.3, 3.0, 1.1, 0.1, 2.0], [5.7, 4.4, 1.5, 0.4, 2.0], [5.4, 3.9, 1.3, 0.4, 2.0], [5.1, 3.5, 1.4, 0.3, 2.0], [5.7, 3.8, 1.7, 0.3, 2.0], [5.1, 3.8, 1.5, 0.3, 2.0], [5.4, 3.4, 1.7, 0.2, 2.0], [5.1, 3.3, 1.7, 0.5, 2.0], [4.8, 3.4, 1.9, 0.2, 2.0], [5.0, 3.0, 1.6, 0.2, 2.0], [5.0, 3.4, 1.6, 0.4, 2.0], [5.2, 3.5, 1.5, 0.2, 2.0], [4.7, 3.2, 1.6, 0.2, 2.0], [5.4, 3.4, 1.5, 0.4, 2.0], [5.2, 4.1, 1.5, 0.1, 2.0], [5.5, 4.2, 1.4, 0.2, 2.0], [4.9, 3.1, 1.5, 0.1, 2.0], [5.5, 3.5, 1.3, 0.2, 2.0], [4.9, 3.1, 1.5, 0.1, 2.0], [4.4, 3.0, 1.3, 0.2, 2.0], [5.1, 3.4, 1.5, 0.2, 2.0], [5.0, 3.5, 1.3, 0.3, 2.0], [4.5, 2.3, 1.3, 0.3, 2.0], [5.0, 3.5, 1.6, 0.6, 2.0], [5.1, 3.8, 1.9, 0.4, 2.0], [4.8, 3.0, 1.4, 0.3, 2.0], [4.6, 3.2, 1.4, 0.2, 2.0], [5.3, 3.7, 1.5, 0.2, 2.0], 

In [ ]:
#numpy array conversion

train = np.array(Train)
validation = np.array(Validation)
test = np.array(Test)

In [ ]:
#Train, test, validation split with probability

import random

Train = []
Test = []
Validation = []
X=[]
for i in range(0, len(X)):
  a=[]
  a.append(X[i][0])
  a.append(X[i][1])
  a.append(y[i])
  num = random.uniform(0, 1)
  if(num>0.7 and num <= 0.85):    
    Validation.append(a)
  elif(num>0.85 and num<=1.0):
    Test.append(a)
  else:
    Train.append(a)

print(len(Train))
print(len(Test))
print(len(Validation))



#raining.....update theta
import math
sampleY=[]

dj_BY_Dtheta1=0
dj_BY_Dtheta2=0
dj_BY_Dtheta3=0
lr=.999
theta1=.3
theta2=.4
theta3=.2
for i in range (0,3000):
 
  total_loss=0
  total_dj_BY_Dtheta1=0
  total_dj_BY_Dtheta2=0
  total_dj_BY_Dtheta3=0
    
  for j in range(0,len(Train)):
     
    sampley=Train[j]
    
    z=sampley[0]*theta1+sampley[1]*theta1+theta3
    h=1/(1+math.exp(-z))
    #print("h=",h)
    if(h==0):
      h=.00000000001
      
    lossJ=(-sampley[-1]*math.log(h))-(1-sampley[-1])*math.log(1-h)
    
    total_loss +=lossJ
    
    dj_BY_Dtheta1 = sampley[0]*(h-sampley[-1])
    dj_BY_Dtheta2 = sampley[1]*(h-sampley[-1])
    dj_BY_Dtheta3 = (h-sampley[-1])


    total_dj_BY_Dtheta1 +=dj_BY_Dtheta1
    total_dj_BY_Dtheta2 +=dj_BY_Dtheta3
    total_dj_BY_Dtheta3 +=dj_BY_Dtheta3

  avrg_loss =(1/len(Train))*total_loss
  avrg_dj_BY_Dtheta1 =(1/len(Train))*total_dj_BY_Dtheta1
  avrg_dj_BY_Dtheta2 =(1/len(Train))*total_dj_BY_Dtheta2
  avrg_dj_BY_Dtheta3 =(1/len(Train))*total_dj_BY_Dtheta3

  theta1=theta1-(lr*dj_BY_Dtheta1 )
  theta2=theta2-(lr*dj_BY_Dtheta2 )
  theta3=theta3-(lr*dj_BY_Dtheta3 )


  print(avrg_loss)


#validation?testings
accuracy=0
count=0
sampleX=[]
for i in range(0, len(Validation)):
  sampleX=Validation[i]
  z=sampleX[0]*theta1+sampleX[1]*theta2+theta3
  h=1/(1+math.exp(-z))
  if(h>=.5):
    h=1
  else:
    h=0
       
  if sampleX[-1]==h:
    count +=1

accuracy=(count/len(Validation))*100
print("accuracy =",accuracy)

0
0
0


ZeroDivisionError: ignored

In [ ]:
#KNN algo -> don't even think about copying from here
from collections import Counter
import math
import numpy as np
import math


val=[]

tra=[]
allDistance=[]

accuracy=0
count=0
for i in range(0, len(Validation)):
  a0=0
  a1=0 
  a2=0
  
  val=Validation[i]
 
  for j in range(0,len(Train)):
          tra=Train[j]
          distance=math.sqrt(math.pow(tra[0]-val[0],2)+math.pow(tra[1]-val[1],2)+math.pow(tra[2]-val[2],2)+math.pow(tra[3]-val[3],2))
          allDistance.append([distance,tra[-1]])
    
  
  allDistance = sorted(allDistance, key=lambda x: x[0])
  

  
  for k in range(0,10):
        if allDistance[k][1]==0.0:
            a0=a0+1
        elif allDistance[k][1]==1.0 :
            a1=a1+1
        else:
           a2=a2+1
  if a0 > a1 and a0 > a2:
    if val[-1]==0.0:
      count=count+1
      
  elif a1 > a0 and a1 > a2:
    if val[-1]==1.0:
       count=count+1
          
  else:
    if val[-1]==2.0:
       count=count+1
accuracy=(count/len(Validation))*100
print("Accuracy =",accuracy)


Accuracy = 22.22222222222222


In [ ]:
from collections import Counter
import math
import operator

def euclidean_distance(point1, point2,sublength):
    distance = 0
    for i in range(len(point1)):
        distance += math.pow(point1[i] - point2[i], 2)
    return math.sqrt(distance)


def knn(data, query, k, distances):
  n_distances=[]
  legth=len(test)-1
  for x in range(len(train)):
    dist=euclidean_distance(test[x], train[x],length)
    n_distances.append((dist, index))
    sorted_n_distances=sorted(n_distances)
    nearest_pick=sorted_n_distances[:k]
    
    for i in n_distances:
      true_sample=0
      if nearest_pick[x] in test[x]
         true_sample+=1
        
        def acuuracy(test,prediction)
        right=0
        for x in range(len(tset)):
          if testx[-1] in predicttion[x]:
            right+=1
            return (right/float(len(test)))*100.0




  

SyntaxError: ignored

In [ ]:
#sklearn

from sklearn.datasets import load_iris
dataset = load_iris()

print(dataset.data[0:4])
print(dataset.target[0:4])

x= dataset.data
y= dataset.target


[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]]
[0 0 0 0]


In [ ]:

print(y)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
